name: ai

services:
  stable-diffusion:
    build:
      context: stable-diffusion
      dockerfile: Dockerfile
    container_name: stable-diffusion
    volumes:
      - ./stable-diffusion/models:/home/myuser/stable-diffusion-webui/models
      - ./stable-diffusion/outputs:/home/myuser/stable-diffusion-webui/outputs
      - stable-diffusion-repositories:/home/myuser/stable-diffusion-webui/repositories
    ports:
      - 7860:7860
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama:
    image: ollama/ollama:0.5.7
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - 11434:11434
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  open-webui:
    image:  ghcr.io/open-webui/open-webui:0.5.7
    container_name: open-webui
    ports:
      - 3000:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - ENABLE_SIGNUP=true
      - OLLAMA_BASE_URL=http://ollama:11434
      - ENABLE_IMAGE_GENERATION=true
      - IMAGE_GENERATION_ENGINE=automatic1111
      - AUTOMATIC1111_BASE_URL=http://stable-diffusion:7860
      - IMAGE_GENERATION_ENGINE=v1-5-pruned-emaonly.safetensors
      - IMAGE_STEPS=20
    restart: unless-stopped
    depends_on:
      - stable-diffusion
      - ollama

volumes:
  stable-diffusion-repositories:
  ollama:
  open-webui:
